const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('db:get-settings'),
  saveSetting: (key, value) => ipcRenderer.invoke('db:save-setting', key, value),
  getTables: () => ipcRenderer.invoke('db:get-tables'),
  updateTablePrice: (tableNumber, price) => ipcRenderer.invoke('db:update-table-price', tableNumber, price),
  getRunningSessions: () => ipcRenderer.invoke('db:get-running-sessions'),
  getSessionByTable: (tableNumber) => ipcRenderer.invoke('db:get-session-by-table', tableNumber),
  startGame: (tableNumber, player1, player2, matchType, player3, player4) => ipcRenderer.invoke('db:start-game', tableNumber, player1, player2, matchType, player3, player4),
  endGame: (sessionId) => ipcRenderer.invoke('db:end-game', sessionId),
  addGame: (sessionId, winner, loser) => ipcRenderer.invoke('db:add-game', sessionId, winner, loser),
  getSessionGames: (sessionId) => ipcRenderer.invoke('db:get-session-games', sessionId),
  startNextGame: (sessionId, p1, p2, p3, p4, matchType) => ipcRenderer.invoke('db:start-next-game', sessionId, p1, p2, p3, p4, matchType),
  endCurrentGame: (sessionId, winner, loser) => ipcRenderer.invoke('db:end-current-game', sessionId, winner, loser),
  getRunningGame: (sessionId) => ipcRenderer.invoke('db:get-running-game', sessionId),
  addCanteenOrder: (sessionId, itemName, quantity, price) => ipcRenderer.invoke('db:add-canteen-order', sessionId, itemName, quantity, price),
  getCanteenOrders: (sessionId) => ipcRenderer.invoke('db:get-canteen-orders', sessionId),
  getCompletedSessions: () => ipcRenderer.invoke('db:get-completed-sessions'),
  getMatchHistoryByTable: (tableNumber) => ipcRenderer.invoke('db:get-match-history-by-table', tableNumber),
  getDailyReport: (date, tableNumber) => ipcRenderer.invoke('db:get-daily-report', date, tableNumber),
  getTableUsageReport: () => ipcRenderer.invoke('db:get-table-usage-report'),
  getPlayerHistory: () => ipcRenderer.invoke('db:get-player-history'),
  ensurePlayer: (name) => ipcRenderer.invoke('db:ensure-player', name),
  getInvoices: (tableNumber) => ipcRenderer.invoke('db:get-invoices', tableNumber),
  getInvoice: (id) => ipcRenderer.invoke('db:get-invoice', id),
  getInvoicesByDate: (date, tableNumber) => ipcRenderer.invoke('db:get-invoices-by-date', date, tableNumber),
  getAllSessions: () => ipcRenderer.invoke('db:get-all-sessions'),
  getLatestSessionByTable: (tableNumber) => ipcRenderer.invoke('db:get-latest-session-by-table', tableNumber),
  completeTableOrder: (tableNumber) => ipcRenderer.invoke('db:complete-table-order', tableNumber),
  updateInvoicePayment: (invoiceId, paymentMethod, discount, discountType, notes) => ipcRenderer.invoke('db:update-invoice-payment', invoiceId, paymentMethod, discount, discountType, notes),
  printBill: (htmlContent) => ipcRenderer.invoke('print:bill', htmlContent),
});
