const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('db:get-settings'),
  saveSetting: (key, value) => ipcRenderer.invoke('db:save-setting', key, value),
  getTables: () => ipcRenderer.invoke('db:get-tables'),
  updateTablePrice: (tableNumber, price) => ipcRenderer.invoke('db:update-table-price', tableNumber, price),
  getRunningSessions: () => ipcRenderer.invoke('db:get-running-sessions'),
  getSessionByTable: (tableNumber) => ipcRenderer.invoke('db:get-session-by-table', tableNumber),
  startGame: (tableNumber, player1, player2, matchType, player3, player4) => ipcRenderer.invoke('db:start-game', tableNumber, player1, player2, matchType, player3, player4),
  endGame: (sessionId) => ipcRenderer.invoke('db:end-game', sessionId),
  addGame: (sessionId, winner, loser) => ipcRenderer.invoke('db:add-game', sessionId, winner, loser),
  getSessionGames: (sessionId) => ipcRenderer.invoke('db:get-session-games', sessionId),
  startNextGame: (sessionId, p1, p2, p3, p4, matchType) => ipcRenderer.invoke('db:start-next-game', sessionId, p1, p2, p3, p4, matchType),
  endCurrentGame: (sessionId, winner, loser) => ipcRenderer.invoke('db:end-current-game', sessionId, winner, loser),
  getRunningGame: (sessionId) => ipcRenderer.invoke('db:get-running-game', sessionId),
  addCanteenOrder: (sessionId, itemName, quantity, price) => ipcRenderer.invoke('db:add-canteen-order', sessionId, itemName, quantity, price),
  getCanteenOrders: (sessionId) => ipcRenderer.invoke('db:get-canteen-orders', sessionId),
  getCompletedSessions: () => ipcRenderer.invoke('db:get-completed-sessions'),
  getMatchHistoryByTable: (tableNumber) => ipcRenderer.invoke('db:get-match-history-by-table', tableNumber),
  getDailyReport: (date, tableNumber) => ipcRenderer.invoke('db:get-daily-report', date, tableNumber),
  getTableUsageReport: () => ipcRenderer.invoke('db:get-table-usage-report'),
  getPlayerHistory: () => ipcRenderer.invoke('db:get-player-history'),
  ensurePlayer: (name) => ipcRenderer.invoke('db:ensure-player', name),
  getInvoices: (tableNumber) => ipcRenderer.invoke('db:get-invoices', tableNumber),
  getInvoice: (id) => ipcRenderer.invoke('db:get-invoice', id),
  getInvoicesByDate: (date, tableNumber) => ipcRenderer.invoke('db:get-invoices-by-date', date, tableNumber),
  getAllSessions: () => ipcRenderer.invoke('db:get-all-sessions'),
  getLatestSessionByTable: (tableNumber) => ipcRenderer.invoke('db:get-latest-session-by-table', tableNumber),
  completeTableOrder: (tableNumber) => ipcRenderer.invoke('db:complete-table-order', tableNumber),
  updateInvoicePayment: (invoiceId, paymentMethod, discount, discountType, notes) => ipcRenderer.invoke('db:update-invoice-payment', invoiceId, paymentMethod, discount, discountType, notes),
  printBill: (htmlContent) => ipcRenderer.invoke('print:bill', htmlContent),

  getStaff: () => ipcRenderer.invoke('db:get-staff'),
  getStaffMember: (id) => ipcRenderer.invoke('db:get-staff-member', id),
  addStaff: (name, role, username, password, phone, email, salary) => ipcRenderer.invoke('db:add-staff', name, role, username, password, phone, email, salary),
  updateStaff: (id, name, role, username, password, phone, email, salary, status) => ipcRenderer.invoke('db:update-staff', id, name, role, username, password, phone, email, salary, status),
  deleteStaff: (id) => ipcRenderer.invoke('db:delete-staff', id),
  staffLogin: (staffId) => ipcRenderer.invoke('db:staff-login', staffId),
  staffLogout: (sessionId) => ipcRenderer.invoke('db:staff-logout', sessionId),
  getStaffSessions: () => ipcRenderer.invoke('db:get-staff-sessions'),
  getShiftReports: (staffId) => ipcRenderer.invoke('db:get-shift-reports', staffId),
  addShiftReport: (staffId, date, clockIn, clockOut, notes) => ipcRenderer.invoke('db:add-shift-report', staffId, date, clockIn, clockOut, notes),
  getPerformanceReports: (staffId) => ipcRenderer.invoke('db:get-performance-reports', staffId),
  addPerformanceReport: (staffId, reviewDate, rating, notes) => ipcRenderer.invoke('db:add-performance-report', staffId, reviewDate, rating, notes),

  getMembershipPlans: () => ipcRenderer.invoke('db:get-membership-plans'),
  addMembershipPlan: (name, durationDays, price, benefits) => ipcRenderer.invoke('db:add-membership-plan', name, durationDays, price, benefits),
  updateMembershipPlan: (id, name, durationDays, price, benefits, status) => ipcRenderer.invoke('db:update-membership-plan', id, name, durationDays, price, benefits, status),
  deleteMembershipPlan: (id) => ipcRenderer.invoke('db:delete-membership-plan', id),
});
